name: CI

on:
  pull_request:

jobs:
  ci_build:
    name: (CI) Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: pip install setuptools

      - name: Extract reporter package version
        working-directory: greener_reporter
        run: |
          export PKG_VERSION=$(python setup.py --version | tr -d '[:space:]')
          echo "GREENER_REPORTER_PKG_VERSION=$PKG_VERSION" >> "$GITHUB_ENV"

      - name: Extract servermock package version
        working-directory: greener_servermock
        run: |
          export PKG_VERSION=$(python setup.py --version | tr -d '[:space:]')
          echo "GREENER_SERVERMOCK_PKG_VERSION=$PKG_VERSION" >> "$GITHUB_ENV"

      - name: Verify reporter and servermock version
        run: |
          if [ "$GREENER_REPORTER_PKG_VERSION" != "$GREENER_SERVERMOCK_PKG_VERSION" ]; then
            echo "Error: reporter and servermock must have the same version"
            exit 1
          fi

      - name: Extract reporter version
        run: |
          export GREENER_REPORTER_VERSION=$(cat DEP_VERSION_REPORTER | tr -d '[:space:]')
          echo "GREENER_REPORTER_VERSION=$GREENER_REPORTER_VERSION" >> "$GITHUB_ENV"

      - name: Download reporter includes/libs
        run: |
          export GREENER_REPORTER_RELEASE=https://github.com/cephei8/greener-reporter/releases/download/$GREENER_REPORTER_VERSION
          wget $GREENER_REPORTER_RELEASE/greener-reporter-lib-linux-x64.tar.gz
          wget $GREENER_REPORTER_RELEASE/greener-servermock-lib-linux-x64.tar.gz

          tar -xzf ./greener-reporter-lib-linux-x64.tar.gz -C greener_reporter/greener_reporter
          tar -xzf ./greener-servermock-lib-linux-x64.tar.gz -C greener_servermock/greener_servermock

      - run: pip install -r requirements.txt
      - run: pytest -v .
